// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwiuxbTVK9RV3wcEMOfdiI12KsqvXkEiw',
    appId: '1:928093717935:web:175509c4c8cb93a449db5a',
    messagingSenderId: '928093717935',
    projectId: 'note-app-e2ec5',
    authDomain: 'note-app-e2ec5.firebaseapp.com',
    storageBucket: 'note-app-e2ec5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnZlCBNvGX1EKMEPVTBWiKtYlZJ1A_tn4',
    appId: '1:928093717935:android:9d98cc1b2c42f76e49db5a',
    messagingSenderId: '928093717935',
    projectId: 'note-app-e2ec5',
    storageBucket: 'note-app-e2ec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0kKA97dpYT-pdCH34D-YIFr62k8t6yNI',
    appId: '1:928093717935:ios:04c851dcf63ab6cb49db5a',
    messagingSenderId: '928093717935',
    projectId: 'note-app-e2ec5',
    storageBucket: 'note-app-e2ec5.appspot.com',
    iosClientId: '928093717935-0hfoqm4gopefkudcj2o6a8s4u2q7hlij.apps.googleusercontent.com',
    iosBundleId: 'com.dazai.noteApp',
  );
}
